// <auto-generated />
using GeekShopping.ProductApi.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductApi.Migrations
{
    [DbContext(typeof(MySqlDataContext))]
    [Migration("20230623022111_AddProductDatabase")]
    partial class AddProductDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Category_Name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Image_Url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "TShirt",
                            Description = "description",
                            ImageUrl = "GeekShopping.ProductApi\\ShopImages\\2_no_internet.jpg",
                            Name = "name",
                            Value = 49m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Card Game",
                            Description = "Tcg Magic",
                            ImageUrl = "GeekShopping.ProductApi\\ShopImages\\10_milennium_falcon.jpg",
                            Name = "Magic",
                            Value = 99m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Jogo de tabuleiro",
                            Description = "Jogo de tabuleiro",
                            ImageUrl = "GeekShopping.ProductApi\\ShopImages\\9_neil.jpg",
                            Name = "Warhammer",
                            Value = 299m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
